'%test':
  quarkus:
    datasource:
      db-kind: h2

'%dev':
  quarkus:
    datasource:
      db-kind: mysql
      username: gestor_financeiro_backend_api
      password: gestor_financeiro_backend_api
      jdbc:
        url: jdbc:mysql://localhost:3306/gestor_financeiro_backend_db
      devservices:
        enabled: false
    hibernate-orm:
      schema-management:
        strategy: update